jwtSecret = "1515"
[database]
url = "root:151500@(localhost)/learning?charset=utf8mb4&parseTime=True&loc=Local"
[path]
avatar = "./static/avatar"
file = "./static/resource"
frontend = "./static/frontend"
video = "./static/video"
cover = "./static/cover"
[redis]
addr = "localhost:6379"
password = ""